version: '3'

services:
    database:
        container_name: database
        build:
            context: ./.docker/database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/database/data:/var/lib/mysql

    php-fpm:
        container_name: php-fpm
        build:
            context: ./.docker/php-fpm
        depends_on:
            - database
        working_dir: /var/www
        volumes:
            - ./www:/var/www
    
    nginx:
        container_name: nginx
        build:
            context: ./.docker/nginx
        volumes:
            - ./www:/var/www
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/sites/:/etc/nginx/sites-available
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./.docker/logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - "8000:80"
